// localStorage.clear()
const employees = [
  {
    id: 1,
    name: "Ravi Sharma",
    email: "ravi.sharma@company.com",
    password: "123",
    number: "+91-9876543210",
    tasks: [
      {
        title: "Prepare monthly report",
        active: 1,
        newTask: 1,
        completed: 0,
        failed: 0,
        description: "Compile the monthly sales data and summarize findings.",
        dueDate: "2024-11-10",
        assignedTo: "Ravi Sharma",
        priority: "High",
        category: "Reporting",
      },
      {
        title: "Team meeting preparation",
        active: 0,
        newTask: 0,
        completed: 1,
        failed: 0,
        description: "Prepare slides for the upcoming team meeting.",
        dueDate: "2024-10-25",
        assignedTo: "Ravi Sharma",
        priority: "Medium",
        category: "Meetings",
      },
      {
        title: "Client follow-up",
        active: 1,
        newTask: 0,
        completed: 0,
        failed: 0,
        description: "Follow up with clients on recent project updates.",
        dueDate: "2024-11-05",
        assignedTo: "Ravi Sharma",
        priority: "High",
        category: "Client Relations",
      },
    ],
    taskCount: {
      active: 2,
      newTask: 1,
      completed: 1,
      failed: 0,
    },
  },
  {
    id: 2,
    name: "Aarti Verma",
    email: "aarti.verma@company.com",
    password: "123",
    number: "+91-9876543211",
    tasks: [
      {
        title: "Update software",
        active: 0,
        newTask: 0,
        completed: 1,
        failed: 0,
        description: "Install the latest updates on all team devices.",
        dueDate: "2024-10-20",
        assignedTo: "Aarti Verma",
        priority: "Low",
        category: "Maintenance",
      },
      {
        title: "Create project proposal",
        active: 1,
        newTask: 1,
        completed: 0,
        failed: 0,
        description: "Draft a proposal for the upcoming client project.",
        dueDate: "2024-11-12",
        assignedTo: "Aarti Verma",
        priority: "High",
        category: "Planning",
      },
      {
        title: "Research competitors",
        active: 1,
        newTask: 0,
        completed: 0,
        failed: 0,
        description: "Conduct research on competing companies and products.",
        dueDate: "2024-11-08",
        assignedTo: "Aarti Verma",
        priority: "Medium",
        category: "Research",
      },
    ],
    taskCount: {
      active: 2,
      newTask: 1,
      completed: 1,
      failed: 0,
    },
  },
  {
    id: 3,
    name: "Priya Singh",
    email: "priya.singh@company.com",
    password: "123",
    number: "+91-9876543212",
    tasks: [
      {
        title: "Inventory audit",
        active: 1,
        newTask: 1,
        completed: 0,
        failed: 0,
        description: "Check and audit the current inventory levels.",
        dueDate: "2024-11-15",
        assignedTo: "Priya Singh",
        priority: "High",
        category: "Audit",
      },
      {
        title: "Staff training session",
        active: 0,
        newTask: 0,
        completed: 1,
        failed: 0,
        description: "Conduct a training session for new staff members.",
        dueDate: "2024-10-30",
        assignedTo: "Priya Singh",
        priority: "Medium",
        category: "Training",
      },
      {
        title: "Product review",
        active: 1,
        newTask: 0,
        completed: 0,
        failed: 0,
        description: "Review feedback on the newly launched product.",
        dueDate: "2024-11-07",
        assignedTo: "Priya Singh",
        priority: "High",
        category: "Product Review",
      },
    ],
    taskCount: {
      active: 2,
      newTask: 1,
      completed: 1,
      failed: 0,
    },
  },
  {
    id: 4,
    name: "Arjun Nair",
    email: "arjun.nair@company.com",
    password: "123",
    number: "+91-9876543213",
    tasks: [
      {
        title: "Website update",
        active: 1,
        newTask: 1,
        completed: 0,
        failed: 0,
        description: "Update website content and improve UX design.",
        dueDate: "2024-11-20",
        assignedTo: "Arjun Nair",
        priority: "High",
        category: "Website Management",
      },
      {
        title: "Monthly newsletter",
        active: 1,
        newTask: 0,
        completed: 0,
        failed: 0,
        description: "Draft and send out the company newsletter.",
        dueDate: "2024-11-10",
        assignedTo: "Arjun Nair",
        priority: "Medium",
        category: "Communications",
      },
    ],
    taskCount: {
      active: 2,
      newTask: 1,
      completed: 0,
      failed: 0,
    },
  },
  {
    id: 5,
    name: "Meera Kapoor",
    email: "meera.kapoor@company.com",
    password: "123",
    number: "+91-9876543214",
    tasks: [
      {
        title: "Customer feedback analysis",
        active: 1,
        newTask: 1,
        completed: 0,
        failed: 0,
        description: "Analyze and summarize recent customer feedback.",
        dueDate: "2024-11-12",
        assignedTo: "Meera Kapoor",
        priority: "High",
        category: "Customer Service",
      },
      {
        title: "Social media campaign",
        active: 1,
        newTask: 0,
        completed: 0,
        failed: 0,
        description: "Plan and execute the next social media campaign.",
        dueDate: "2024-11-18",
        assignedTo: "Meera Kapoor",
        priority: "Medium",
        category: "Marketing",
      },
    ],
    taskCount: {
      active: 2,
      newTask: 1,
      completed: 0,
      failed: 0,
    },
  },
];

const admin = {
  id: 101,
  email: "admin@company.com",
  password: "123",
};

export const setLocalStorage = () => {
  localStorage.setItem("employees", JSON.stringify(employees));
  localStorage.setItem("admin", JSON.stringify(admin));
};

export const getLocalStorage = () => {
  const employees = JSON.parse(localStorage.getItem("employees"));
  const admin = JSON.parse(localStorage.getItem("admin"));
  return { employees, admin };
};

