const employees = [
  {
    id: 1,
    email: "alice.johnson@company.com",
    password: "123",
    tasks: [
      {
        title: "Prepare monthly report",
        active: true,
        newTask: true,
        completed: false,
        failed: false,
        description: "Compile the monthly sales data and summarize findings.",
        dueDate: "2024-11-10",
        assignedTo: "Alice Johnson",
        priority: "High",
        category: "Reporting",
      },
      {
        title: "Team meeting preparation",
        active: false,
        newTask: false,
        completed: true,
        failed: false,
        description: "Prepare slides for the upcoming team meeting.",
        dueDate: "2024-10-25",
        assignedTo: "Alice Johnson",
        priority: "Medium",
        category: "Meetings",
      },
      {
        title: "Client follow-up",
        active: true,
        newTask: false,
        completed: false,
        failed: false,
        description: "Follow up with clients on recent project updates.",
        dueDate: "2024-11-05",
        assignedTo: "Alice Johnson",
        priority: "High",
        category: "Client Relations",
      },
    ],
  },
  {
    id: 2,
    email: "bob.smith@company.com",
    password: "123",
    tasks: [
      {
        title: "Update software",
        active: false,
        newTask: false,
        completed: true,
        failed: false,
        description: "Install the latest updates on all team devices.",
        dueDate: "2024-10-20",
        assignedTo: "Bob Smith",
        priority: "Low",
        category: "Maintenance",
      },
      {
        title: "Create project proposal",
        active: true,
        newTask: true,
        completed: false,
        failed: false,
        description: "Draft a proposal for the upcoming client project.",
        dueDate: "2024-11-12",
        assignedTo: "Bob Smith",
        priority: "High",
        category: "Planning",
      },
      {
        title: "Research competitors",
        active: true,
        newTask: false,
        completed: false,
        failed: false,
        description: "Conduct research on competing companies and products.",
        dueDate: "2024-11-08",
        assignedTo: "Bob Smith",
        priority: "Medium",
        category: "Research",
      },
    ],
  },
  {
    id: 3,
    email: "carol.white@company.com",
    password: "123",
    tasks: [
      {
        title: "Inventory audit",
        active: true,
        newTask: true,
        completed: false,
        failed: false,
        description: "Check and audit the current inventory levels.",
        dueDate: "2024-11-15",
        assignedTo: "Carol White",
        priority: "High",
        category: "Audit",
      },
      {
        title: "Staff training session",
        active: false,
        newTask: false,
        completed: true,
        failed: false,
        description: "Conduct a training session for new staff members.",
        dueDate: "2024-10-30",
        assignedTo: "Carol White",
        priority: "Medium",
        category: "Training",
      },
      {
        title: "Product review",
        active: true,
        newTask: false,
        completed: false,
        failed: false,
        description: "Review feedback on the newly launched product.",
        dueDate: "2024-11-07",
        assignedTo: "Carol White",
        priority: "High",
        category: "Product Review",
      },
    ],
  },
  {
    id: 4,
    email: "david.brown@company.com",
    password: "123",
    tasks: [
      {
        title: "Website update",
        active: true,
        newTask: true,
        completed: false,
        failed: false,
        description: "Update website content and improve UX design.",
        dueDate: "2024-11-20",
        assignedTo: "David Brown",
        priority: "High",
        category: "Website Management",
      },
      {
        title: "Monthly newsletter",
        active: true,
        newTask: false,
        completed: false,
        failed: false,
        description: "Draft and send out the company newsletter.",
        dueDate: "2024-11-10",
        assignedTo: "David Brown",
        priority: "Medium",
        category: "Communications",
      },
    ],
  },
  {
    id: 5,
    email: "eve.adams@company.com",
    password: "123",
    tasks: [
      {
        title: "Customer feedback analysis",
        active: true,
        newTask: true,
        completed: false,
        failed: false,
        description: "Analyze and summarize recent customer feedback.",
        dueDate: "2024-11-12",
        assignedTo: "Eve Adams",
        priority: "High",
        category: "Customer Service",
      },
      {
        title: "Social media campaign",
        active: true,
        newTask: false,
        completed: false,
        failed: false,
        description: "Plan and execute the next social media campaign.",
        dueDate: "2024-11-18",
        assignedTo: "Eve Adams",
        priority: "Medium",
        category: "Marketing",
      },
    ],
  },
];

const admin = {
  id: 101,
  email: "admin@company.com",
  password: "123",
};

export const setLocalStorage = () => {
  localStorage.setItem("employees", JSON.stringify(employees));
  localStorage.setItem("admin", JSON.stringify(admin));
};
export const getLocalStorage = () => {
  const employees = JSON.parse(localStorage.getItem("employees"));
  const admin = JSON.parse(localStorage.getItem("admin"));
  return { employees, admin };
};
